---
abstract: unknown
author:
  - 'Youri project <youri@zarb.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Youri-Package-RPM-Generator
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: 0
  File::Which: 0
  Test::Exception: 0
  Text::Template: 0
  URPM: 0
  version: 0
version: v0.1.3
